name: Windows Build and Hash Update

on:
  push:
    branches:
      - main

jobs:
  build-and-hash:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build Solution
        run: msbuild AnarchyInjector.sln /p:Configuration=Release /p:Platform=x86

      - name: Generate MD5 Hash
        shell: powershell
        run: |
          $exePath = "Release\\AnarchyInjector.exe"
          $md5 = Get-FileHash $exePath -Algorithm MD5 | Select-Object -ExpandProperty Hash
          echo "MD5 Hash: $md5"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AnarchyInjector
          path: Release/AnarchyInjector.exe
